/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "blast-furnace": "/blast-furnace";
    "blast-furnace_analysis": "/blast-furnace/analysis";
    "blast-furnace_analysis_correlation-analysis": "/blast-furnace/analysis/correlation-analysis";
    "blast-furnace_analysis_historical-analysis": "/blast-furnace/analysis/historical-analysis";
    "blast-furnace_data-management": "/blast-furnace/data-management";
    "blast-furnace_data-management_data-collection": "/blast-furnace/data-management/data-collection";
    "blast-furnace_data-management_data-preprocessing": "/blast-furnace/data-management/data-preprocessing";
    "blast-furnace_data-management_data-storage": "/blast-furnace/data-management/data-storage";
    "blast-furnace_monitoring": "/blast-furnace/monitoring";
    "blast-furnace_monitoring_anomaly-detection": "/blast-furnace/monitoring/anomaly-detection";
    "blast-furnace_monitoring_early-warning": "/blast-furnace/monitoring/early-warning";
    "blast-furnace_monitoring_quality-dashboard": "/blast-furnace/monitoring/quality-dashboard";
    "blast-furnace_monitoring_real-time-monitoring": "/blast-furnace/monitoring/real-time-monitoring";
    "blast-furnace_optimization": "/blast-furnace/optimization";
    "blast-furnace_optimization_model-deployment": "/blast-furnace/optimization/model-deployment";
    "blast-furnace_optimization_model-evaluation": "/blast-furnace/optimization/model-evaluation";
    "blast-furnace_optimization_model-training": "/blast-furnace/optimization/model-training";
    "blast-furnace_optimization_scheme-comparison": "/blast-furnace/optimization/scheme-comparison";
    "blast-furnace_system": "/blast-furnace/system";
    "blast-furnace_system_role-management": "/blast-furnace/system/role-management";
    "blast-furnace_system_system-logs": "/blast-furnace/system/system-logs";
    "blast-furnace_system_system-settings": "/blast-furnace/system/system-settings";
    "blast-furnace_system_user-management": "/blast-furnace/system/user-management";
    "home": "/home";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "redirect": "/redirect";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "blast-furnace"
    | "home"
    | "login"
    | "redirect"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "blast-furnace_analysis_correlation-analysis"
    | "blast-furnace_analysis_historical-analysis"
    | "blast-furnace_data-management_data-collection"
    | "blast-furnace_data-management_data-preprocessing"
    | "blast-furnace_data-management_data-storage"
    | "blast-furnace_monitoring_anomaly-detection"
    | "blast-furnace_monitoring_early-warning"
    | "blast-furnace_monitoring_quality-dashboard"
    | "blast-furnace_monitoring_real-time-monitoring"
    | "blast-furnace_optimization_model-deployment"
    | "blast-furnace_optimization_model-evaluation"
    | "blast-furnace_optimization_model-training"
    | "blast-furnace_optimization_scheme-comparison"
    | "blast-furnace_system_role-management"
    | "blast-furnace_system_system-logs"
    | "blast-furnace_system_system-settings"
    | "blast-furnace_system_user-management"
    | "home"
    | "login"
    | "redirect"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
