/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/403/index.vue"),
  "blast-furnace_analysis_correlation-analysis": () => import("@/views/blast-furnace/analysis/correlation-analysis/index.vue"),
  "blast-furnace_analysis_historical-analysis": () => import("@/views/blast-furnace/analysis/historical-analysis/index.vue"),
  "blast-furnace_data-management_data-collection": () => import("@/views/blast-furnace/data-management/data-collection/index.vue"),
  "blast-furnace_data-management_data-preprocessing": () => import("@/views/blast-furnace/data-management/data-preprocessing/index.vue"),
  "blast-furnace_data-management_data-storage": () => import("@/views/blast-furnace/data-management/data-storage/index.vue"),
  "blast-furnace_monitoring_anomaly-detection": () => import("@/views/blast-furnace/monitoring/anomaly-detection/index.vue"),
  "blast-furnace_monitoring_early-warning": () => import("@/views/blast-furnace/monitoring/early-warning/index.vue"),
  "blast-furnace_monitoring_quality-dashboard": () => import("@/views/blast-furnace/monitoring/quality-dashboard/index.vue"),
  "blast-furnace_monitoring_real-time-monitoring": () => import("@/views/blast-furnace/monitoring/real-time-monitoring/index.vue"),
  "blast-furnace_optimization_model-deployment": () => import("@/views/blast-furnace/optimization/model-deployment/index.vue"),
  "blast-furnace_optimization_model-evaluation": () => import("@/views/blast-furnace/optimization/model-evaluation/index.vue"),
  "blast-furnace_optimization_model-training": () => import("@/views/blast-furnace/optimization/model-training/index.vue"),
  "blast-furnace_optimization_scheme-comparison": () => import("@/views/blast-furnace/optimization/scheme-comparison/index.vue"),
  "blast-furnace_system_role-management": () => import("@/views/blast-furnace/system/role-management/index.vue"),
  "blast-furnace_system_system-logs": () => import("@/views/blast-furnace/system/system-logs/index.vue"),
  "blast-furnace_system_system-settings": () => import("@/views/blast-furnace/system/system-settings/index.vue"),
  "blast-furnace_system_user-management": () => import("@/views/blast-furnace/system/user-management/index.vue"),
  home: () => import("@/views/home/index.vue"),
  login: () => import("@/views/login/index.vue"),
  redirect: () => import("@/views/redirect/index.vue"),
};
